threemeals-master/fridge/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings


from fridge.views import *
#
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'ingredients', IngredientViewSet)

urlpatterns=[
    url(r'^$', FridgeHomeView.as_view(), name='recommendation'),
    url(r'^ingredient/$', IngredientHomeView.as_view(), name='ingredient'),
    url(r'^scrap/$', ScrapHomeView.as_view(), name="scrap"),
    url(r'^shopping/$', ShoppingHomeView.as_view(), name="shopping"),
    url(r'^ingredient/add/$', AddIngredient.as_view(), name="addinng"),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

threemeals-master/myblog/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings

from myblog.views import HomeView
from myblog.views import UserCreateView, UserCreateDoneTV


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^fridge/', include('fridge.urls', namespace='fridge')),

    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

threemeals-master/fridge/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

class Ingredient(models.Model):
    ingredientName= models.CharField(max_length=50)
    type=models.IntegerField(default=0)
    category=models.IntegerField(default=0)
    storageMethod=models.IntegerField(default=0)
    unit=models.CharField(max_length=100)
    defaultValue=models.IntegerField(default=0)
    ingredientCode=models.IntegerField(default=0)

threemeals-master/fridge/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView

from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from myblog.views import LoginRequiredMixin

from fridge.models import Ingredient
from rest_framework import viewsets
from fridge.serializers import IngredientSerializer

class FridgeHomeView(TemplateView):
    template_name = 'fridge/recom_list.html'

class IngredientHomeView(TemplateView):
    template_name = 'fridge/ingredient_list.html'

class ScrapHomeView(TemplateView):
    template_name = 'fridge/scrap_list.html'

class ShoppingHomeView(TemplateView):
    template_name = 'fridge/shopping_memo.html'

class AddIngredient(TemplateView):
	template_name = 'fridge/addingredient.html'
	
	def get_ingre(self):
		ingredient_type = int(self.request.GET.get('type') or '0')
		if ingredient_type == 0:
			ingredients = Ingredient.objects.all()
		else:
			ingredients = Ingredient.objects.filter(type=ingredient_type)
		context = {'ingredients': ingredients}
		return context

class IngredientViewSet(viewsets.ModelViewSet):
	queryset = Ingredient.objects.all()
	serializer_class = IngredientSerializer
	lookup_field = 'type'


	def get_queryset(self):
		ingredient_type = int(self.request.GET.get('type') or '0')
		if ingredient_type == 0:
			ingredients = Ingredient.objects.all()
		else:
			ingredients = Ingredient.objects.filter(type=ingredient_type)

		queryset = ingredients
		return queryset



# class MealCreateView(LoginRequiredMixin, CreateView):
#     model = MealPref
#     fields = ['morning', 'lunch', 'dinner']
#     success_url = reverse_lazy('mealpref:index')
#     def form_valid(self, form):
#         form.instance.pref_user = self.request.user
#         return super(MealCreateView, self).form_valid(form)
#
# class MealChangeLV(LoginRequiredMixin, ListView):
#     template_name = 'mealpref/mealpref_change_list.html'
#
#     def get_queryset(self):
#         return MealPref.objects.filter(pref_user=self.request.user)
#
# class MealUpdateView(LoginRequiredMixin, UpdateView):
#     model = MealPref
#     fields = ['morning', 'lunch', 'dinner']
#     success_url = reverse_lazy('mealpref:index')
#
# class MealDeleteView(LoginRequiredMixin, DeleteView):
#     model = MealPref
#     success_url = reverse_lazy('mealpref:index')

threemeals-master/myblog/views.py
from django.views.generic.base import TemplateView

from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

from django.contrib.auth.decorators import login_required

class HomeView(TemplateView):
    template_name = 'home.html'

#--- User Creation
class UserCreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')

class UserCreateDoneTV(TemplateView):
    template_name = 'registration/register_done.html'

class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view)

threemeals-master/fridge/templates/fridge/addingredient.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <title>채워넣기</title>
</head>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "fridge/adding.css" %}" />
<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}"/>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>


<body>
    <div class="search-container">
        <div class="search-box"><!--재료명을 입력하세요 부분 -->
            <input type="text" class="search-txt" placeholder="재료명을 입력하세요">
            <a class="search-btn" href="#">
                <i class="fas fa-search"></i>
            </a>

        </div>
    </div>
    <div class="ingredient-container">
        <div class="total-lists">
            <div class="categories">
                <p>왼쪽 카테고리</p>
                <ul>
                    <li><a class="category-button" id="type-1">정육계란류</a></li>
                    <li><a class="category-button" id="type-2">수산물</a></li>
                    <li><a class="category-button" id="type-3">과일/채소</a></li>
                    <li><a class="category-button" id="type-4">곡물/견과류</a></li>
                    <li><a class="category-button" id="type-5">유제품</a></li>
                    <li><a class="category-button" id="type-6">가공품</a></li>
                    <li><a class="category-button" id="type-7">밑반찬</a></li>
                </ul>
            </div>
            <div class="sub-categories" id="sub-categories">
                <p>오른쪽 재료들</p>
                <div id="ingredients-container">
                </div>
            </div>
        </div>
    </div>
    <div class="chosen-container">
        <div class="sub-categories" id="chosen">
        </div>
        <div class="button-container">
            <center><button id="submit-ingredients">추가</button></center>
            <!-- <i class="far fa-plus-circle" id="submit-ingredients"></i> -->
        </div>
    </div>
    <script>
(function ($, window) {
    let dict = {};
    function ingredientContainerTemplate(data) {
        let html = "";
        html += `<ul>`;
        html += `<li class="ingredient-item" id="ingredient-${data.ingredientCode}">${data.ingredientName}</li>`;
        html += `</ul>`;
        return html;
    }
    function ingredientContainerTemplates(datas) {
        let html = "";
        for (let i = 0; i < datas.length; i++) {
            html += ingredientContainerTemplate(datas[i]);
        }
        return html;
    }
    function setIngredientsContainer(datas) {
        $("#ingredients-container").children().remove();
        $("#ingredients-container").append(ingredientContainerTemplates(datas));
    }
    function selectedIngredientTemplate(data) {
        let html = "";
        html += `<ul>`;
        html += `<li class="chosen-ingredient-item" id="chosen-ingredient-${data.ingredientCode}">${data.ingredientName}</li>`;
        html += `</ul>`;
        return html;
    }
    function addSelectedIngredient(data) {
        const $e = $(`#chosen-ingredient-${data.ingredientCode}`);
        if ($e.get(0) !== undefined) {
            return;
        }
        $("#chosen").append(selectedIngredientTemplate(data));
    }
    $(".category-button").on("click", function(e) {
        const $this = $(this);
        const $id = Number($this.get(0).id.split("-")[1]);

        $.ajax({
            url: `/fridge/api/ingredients?type=${$id}`
        })
        .done(function(response) {
            for (let i = 0; i < response.length ; i++) {
                if (response[i].ingredientCode in dict) {
                } else {
                    dict[response[i].ingredientCode] = response[i];
                }
            }
            setIngredientsContainer(response);
            didClickIngredientItem();
        })
        .fail(function(error) {
        })
        .always(function() {
            console.log("always");
        });
    });
    function didClickIngredientItem() {
        $(".ingredient-item").off("click");
        $(".ingredient-item").on("click", function(e) {
            const $this = $(this);
            const $id = Number($this.get(0).id.split("-")[1]);

            console.log($id);
            const data = dict[$id];
            addSelectedIngredient(data);
            didClickSelectedIngredientItem();
        });
    }
    $("#submit-ingredients").on("click", function(e) {
        const $selected = $(".chosen-ingredient-item");
        const ids = [];
        for (let i = 0; i < $selected.length; i++) {
            const id = Number($selected[i].id.split("-")[2]);
            ids.push(id);
        }
        const data = {"ingredient_ids": JSON.stringify(ids)};
        $.ajax({
            url: "/fridge/api/ingredients/selected",
            type: "post",
            data: data
        })
        .done(function(response) {
            console.log(response);
        })
        .fail(function(error) {
            console.log(error);
        })
        .always(function() {
            console.log("submit selected ingredients");
        });
    });
    function didClickSelectedIngredientItem() {
        const $e = $(".chosen-ingredient-item");
        $e.off("click");
        $e.on("click", function(e) {
            const $this = $(this);
            $this.remove();
        });
    }
    window.dict = dict;

}($, window)); 
    </script>
</body>
</html>

threemeals-master/fridge/templates/fridge/ingredient_list.html
{% extends "base.html" %}

{% block title %}ingredient_list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "fridge/ingredient_list.css" %}{% endblock %}

{% block content %}
<div id="content">
    <div id="frozen">
        <p>냉동</p>
    </div>
    <div id="cold">
        <p>냉장</p>
    </div>
    <div id="warm">
        <p>실온</p>
    </div>
    <div>
        <p>채워넣기</p>
        {% if object_list %}
        <ul>
            {% for ingredient in object_list %}
            <li>{{ ingredient.ingredientName }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>
{% endblock %}

threemeals-master/fridge/templates/fridge/recom_list.html
{% extends "base.html" %}

{% block title %}recom_list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "fridge/recom_list.css" %}{% endblock %}

{% block content %}
<div id="content">
    <div id="recipe_recom">
        <ul>
            <li>
                계란말이
            </li>
        </ul>
    </div>
    <div id="my_fridge">
        <h5>MY 냉장고</h5>



    </div>
</div>
{% endblock %}

threemeals-master/fridge/templates/fridge/scrap_list.html
{% extends "base.html" %}

{% block title %}scrap_list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "fridge/scrap_list.css" %}{% endblock %}

{% block content %}
<div id="content">
    <p>
        <h4>MY 스크랩 레시피</h4>
        <span>내가 찜!한 레시피를 확인하세요</span>
    </p>

</div>
{% endblock %}

threemeals-master/fridge/templates/fridge/shopping_memo.html
{% extends "base.html" %}

{% block title %}shopping_memo.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "fridge/shopping_memo.css" %}{% endblock %}

{% block content %}
<div id="content">
    <p>
        <h4>장보기메모</h4>
        <span>장볼 재료들의 리스트를 확인하세요</span>
    </p>
    <table>
        <tr>
            <td>과일/채소</td>
        </tr>
        <tr>
            <td>수산물</td>
        </tr>
        <tr>
            <td>양념/소스</td>
        </tr>
    </table>
</div>
{% endblock %}

threemeals-master/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <title>{% block title %}혼밥세끼{% endblock %}</title>
</head>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}" />
<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}"/>

<body>
    <div id="header">
        <h2 class="maintitle">혼밥세끼</h2>

        {% if user.is_active %}
        <h4 class="welcome">환영합니다,
            <strong>{% firstof user.get_short_name user.get_username %}님</strong>
            <a href="{% url 'logout' %}">로그아웃</a>
        </h4>
        {% else %}
        <h4 class="welcome">환영합니다, 게스트 사용자님 /
            <a href="{% url 'login' %}">로그인</a>
            <a href="{% url 'register' %}">회원가입</a>
        </h4>
        {% endif %}
    </div>
    <div id="menu">
        <li><a href ="{% url 'fridge:recommendation' %}">꺼내 먹기</a></li>
        <li><a href ="{% url 'fridge:ingredient' %}">냉장고 관리</a></li>
        <li><a href ="{% url 'fridge:shopping' %}">장보기 메모</a></li>
        <li><a href ="{% url 'fridge:scrap' %}">My 스크랩</a></li>
    </div>

    {% block content %} {% endblock %}
</body>
</html>

threemeals-master/templates/home.html
{% extends "base.html" %}

{% block title %}home.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{% block content %}

<div id="content_home">
    <div id="homeimg">
        <a href="/"><img src="{% static 'img/freezer.jpg' %}" style="height:285px;"/></a>
    </div>
</div>
{% endblock content %}